### ISSUE TITLE
What does this add-in do exactly?

### ISSUE THREAD

**Issue by egkareem** [ivellios/gvChart#4]
Hello, It would be nice to describe what is your add-in does? What problem it is solving? Where is the documentation?

**Comment by ivellios** [comment]
Hey! I have added long-gone readme file. TBH it's been 6 years since I created the code and it was hosted on different site back then. So this is no longer maintained and probably should not be used. I leave it as a legacy of the library that once was quite popular :)

**Comment by egkareem** [comment]
Thank you for your feedback.
